name: Build and Push Docker image
on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Log in to Azure Container Registry
       uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
         username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
         password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
     - name: Build Docker image
       run: docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/mi-imagen:latest
     - name: Push Docker image
       run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/mi-imagen:latest
