name: CI/CD Pipeline
on:
 push:
   branches:
     - main
jobs:
 build-and-deploy:
   runs-on: windows-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1
   - name: Log in to Azure Container Registry
     uses: azure/docker-login@v1
     with:
       login-server: DemoContainerReg.azurecr.io
       username: ${{ secrets.ACR_USERNAME }}
       password: ${{ secrets.ACR_PASSWORD }}
   - name: Build and push Docker image
     run: |
       docker buildx build --push --tag DemoContainerReg.azurecr.io/<nombre-de-tu-imagen>:latest .
   - name: Azure Login
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
   - name: Deploy to Azure Web App
     uses: azure/webapps-deploy@v2
     with:
       app-name: <nombre-de-tu-webapp>
       slot-name: production
       images: <nombre-de-tu-acr>.azurecr.io/WebAppSample:latest
